version: '3'

services:
  client:
    build:
      context: ./
      dockerfile: ./Dockerfile.client
    ports:
      - "3000:3000"
    tty: true

  server:
    build:
      context: ./
      dockerfile: ./Dockerfile.server
    ports:
      - "3333:3333"
    volumes:
      - ./server/src:/app/src
      - ./server/config:/app/config
    tty: true

  crawler:
    build:
      context: ./
      dockerfile: ./Dockerfile.crawler
    command: 'npm run crawl-dev'
    volumes:
      - ./server/src:/app/src
      - ./server/config:/app/config
    tty: true

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
      - ./server/config/db-config:/etc/mongo
    command:
      - "-f"
      - "/etc/mongo/mongod.conf"
  redis:
    image: redis
    ports:
      - "6379:6379"