version: '3'

services:
  client:
    build:
      context: ./
      dockerfile: ./Dockerfile.client
    ports:
      - "3000:3000"
    tty: true

  server:
    build:
      context: ./
      dockerfile: ./Dockerfile.server
    ports:
      - "3333:3333"
    tty: true

  mongo:
    image: mongo
    ports:
      - "27017:27017"
  redis:
    image: redis
    ports:
      - "6379:6379"